export enum NotificationType {
  LIKE = 'LIKE',
  REPLY = 'REPLY',
  FOLLOW = 'FOLLOW',
  MENTION = 'MENTION',
}

export interface NotificationProps {
  id: string
  type: NotificationType
  recipientId: string
  issuerId: string
  postId?: string | null
  read: boolean
  createdAt: Date
  issuer?: {
    username: string
    name: string
    avatar: string | null
  }
  post?: {
    content: string
  }
}

export class Notification {
  constructor(private readonly props: NotificationProps) {}

  get id() {
    return this.props.id
  }
  get type() {
    return this.props.type
  }
  get recipientId() {
    return this.props.recipientId
  }
  get issuerId() {
    return this.props.issuerId
  }
  get postId() {
    return this.props.postId
  }
  get read() {
    return this.props.read
  }
  get createdAt() {
    return this.props.createdAt
  }
  get issuer() {
    return this.props.issuer
  }
  get post() {
    return this.props.post
  }

  static create(
    props: Omit<NotificationProps, 'id' | 'read' | 'createdAt'>
  ): Notification {
    return new Notification({
      ...props,
      id: '', // Will be generated by DB
      read: false,
      createdAt: new Date(),
    })
  }
}
