export const TYPES = {
  PrismaClient: Symbol.for('PrismaClient'),
  PostRepository: Symbol.for('PostRepository'),
  PostQueryProvider: Symbol.for('PostQueryProvider'),
  // Posts
  CreatePostCommandHandler: Symbol.for('CreatePostCommandHandler'),
  DeletePostCommandHandler: Symbol.for('DeletePostCommandHandler'),
  UpdatePostCommandHandler: Symbol.for('UpdatePostCommandHandler'),
  ToggleLikeCommandHandler: Symbol.for('ToggleLikeCommandHandler'),
  ToggleBookmarkCommandHandler: Symbol.for('ToggleBookmarkCommandHandler'),
  GetFeedHandler: Symbol.for('GetFeedHandler'),
  GetFollowingFeedHandler: Symbol.for('GetFollowingFeedHandler'),
  GetPostDetailHandler: Symbol.for('GetPostDetailHandler'),
  GetPostRepliesHandler: Symbol.for('GetPostRepliesHandler'),
  GetTrendingPostsHandler: Symbol.for('GetTrendingPostsHandler'),
  GetBookmarkedPostsHandler: Symbol.for('GetBookmarkedPostsHandler'),
  GetLikedPostsHandler: Symbol.for('GetLikedPostsHandler'),
  GetPostsByTagHandler: Symbol.for('GetPostsByTagHandler'),
  GetPostsWithMediaHandler: Symbol.for('GetPostsWithMediaHandler'),
  GetUserPostsHandler: Symbol.for('GetUserPostsHandler'),
  SearchPostsHandler: Symbol.for('SearchPostsHandler'),
  RecentSearchRepository: Symbol.for('RecentSearchRepository'),
  AddRecentSearchCommandHandler: Symbol.for('AddRecentSearchCommandHandler'),
  GetRecentSearchesHandler: Symbol.for('GetRecentSearchesHandler'),
  DeleteRecentSearchHandler: Symbol.for('DeleteRecentSearchHandler'),
  ClearRecentSearchesHandler: Symbol.for('ClearRecentSearchesHandler'),
  PostController: Symbol.for('PostController'),
  AuraNodeController: Symbol.for('AuraNodeController'),
  NodeActivityService: Symbol.for('NodeActivityService'),
  AuraNodeRepository: Symbol.for('AuraNodeRepository'),
  GetTrendingNodesHandler: Symbol.for('GetTrendingNodesHandler'),
  GetNodeBySlugHandler: Symbol.for('GetNodeBySlugHandler'),
  TuneIntoNodeHandler: Symbol.for('TuneIntoNodeHandler'),

  // Auth
  AuthRepository: Symbol.for('AuthRepository'),
  TokenService: Symbol.for('TokenService'),
  HashService: Symbol.for('HashService'),
  GoogleService: Symbol.for('GoogleService'),
  ImageService: Symbol.for('ImageService'),
  RegisterCommandHandler: Symbol.for('RegisterCommandHandler'),
  LoginCommandHandler: Symbol.for('LoginCommandHandler'),
  GoogleLoginCommandHandler: Symbol.for('GoogleLoginCommandHandler'),
  RefreshTokenCommandHandler: Symbol.for('RefreshTokenCommandHandler'),
  LogoutCommandHandler: Symbol.for('LogoutCommandHandler'),
  GetMeHandler: Symbol.for('GetMeHandler'),
  AuthController: Symbol.for('AuthController'),
  JWT: Symbol.for('JWT'),

  // Users
  UserRepository: Symbol.for('UserRepository'),
  UserQueryProvider: Symbol.for('UserQueryProvider'),
  FollowUserHandler: Symbol.for('FollowUserHandler'),
  UnfollowUserHandler: Symbol.for('UnfollowUserHandler'),
  GetFollowersHandler: Symbol.for('GetFollowersHandler'),
  GetFollowingHandler: Symbol.for('GetFollowingHandler'),
  IsFollowingHandler: Symbol.for('IsFollowingHandler'),
  GetUserByUsernameHandler: Symbol.for('GetUserByUsernameHandler'),
  GetSuggestedUsersHandler: Symbol.for('GetSuggestedUsersHandler'),
  GetUserMeHandler: Symbol.for('GetUserMeHandler'),
  SearchUsersHandler: Symbol.for('SearchUsersHandler'),
  CreateUserHandler: Symbol.for('CreateUserHandler'),
  UpdateUserHandler: Symbol.for('UpdateUserHandler'),
  DeleteUserUseCase: Symbol.for('DeleteUserUseCase'),
  GetUserAchievementsHandler: Symbol.for('GetUserAchievementsHandler'),
  CheckAchievementHandler: Symbol.for('CheckAchievementHandler'),
  GamificationService: Symbol.for('GamificationService'),
  AchievementController: Symbol.for('AchievementController'),
  UserController: Symbol.for('UserController'),
  CacheService: Symbol.for('CacheService'),

  // Notifications
  NotificationRepository: Symbol.for('NotificationRepository'),
  NotificationQueryProvider: Symbol.for('NotificationQueryProvider'),
  GetNotificationsHandler: Symbol.for('GetNotificationsHandler'),
  MarkAsReadHandler: Symbol.for('MarkAsReadHandler'),
  NotificationController: Symbol.for('NotificationController'),
  NotificationService: Symbol.for('NotificationService'),
  EventBus: Symbol.for('EventBus'),
  NotificationListener: Symbol.for('NotificationListener'),

  // Visits
  VisitRepository: Symbol.for('VisitRepository'),
  RecordVisitHandler: Symbol.for('RecordVisitHandler'),
  GetProfileVisitsHandler: Symbol.for('GetProfileVisitsHandler'),
  VisitController: Symbol.for('VisitController'),

  // Subscribers
  AchievementNotificationSubscriber: Symbol.for(
    'AchievementNotificationSubscriber'
  ),
  NodeActivitySubscriber: Symbol.for('NodeActivitySubscriber'),
  AdminController: Symbol.for('AdminController'),
  Logger: Symbol.for('Logger'),
}
